language: ruby
rvm:
- 2.1.1
script: bundle exec middleman build
deploy:
  provider: divshot
  environment:
    master: production
  skip_cleanup: true
  api_key:
    secure: ILIX/2umDVKbpx5STlbfIcAVb8B8FTT6R8w4TFPF+YBQ0ATuPAZQYbGQSHjMSgQpVqFfHbvtKCaSMcCkfO6/juXvk5ybJtCPIH4HQTc79UDOsONxUFCT9PllHhff+c4+am0WhZdXJTlVYtH3O0W6OVghzhp/mIYSMAMtp1KvMYw=
