source "http://rubygems.org"

gem "builder"
gem "redcarpet"
# gem "middleman", "~>2.0.13"
# gem "middleman-blog", "~>0.1.3"
gem "middleman", :path => "../middleman"
gem "middleman-blog", :path => "../middleman-blog"
# gem "middleman-livereload", :path => "../middleman-livereload"
gem "compass-susy-plugin"
gem "rack-codehighlighter"